#+TITLE: Renewal of Vows Ceremony
#+OPTIONS: toc:nil created:nil author:nil h:1

* Welcome Statement

*Minister*: Jen and Rob, it my pleasure to share this special occasion
with you. Many believe that marriage is the last big milestone in a
relationship. But, the wedding day isn't intended to be the final step
at all. Really (as I'm sure you've learned by now) your wedding was
just the beginning. Despite plenty of challenges, you've made it far
enough that we are now blessed today with the opportunity to renew the
vows you made before God all those years ago.

As the Bible reminds us in Corinthians,

#+begin_quote

"Love is patient, love is kind. It does not envy, it does not
boast, it is not proud. It is not rude, it is not self-seeking, 
it is not easily angered, it keeps no record of wrongs. Love does 
not delight in evil but rejoices with the truth. It always protects, 
always trusts, always hopes, and always perseveres. Love never fails."

#+end_quote

At this time, we thank family and friends for joining us to celebrate
this vow renewal. If you were fortunate enough to attend the ceremony
all those years ago during which Jen and Rob initially entered into
marriage, how fortunate you are to have been able to witness the love
and mutual respect these two have cultivated. Today, we are honored to
witness Jen and Rob recommit themselves to one another as a symbolic
commemoration of their continued devotion.

* Wedding Sermon

*Minister*: When you were married, you likely received advice about
building a relationship that would withstand the test of time. Take a
moment to acknowledge and appreciate that, by virtue of your standing
here before me today, that you have passed this test with flying
colors. The road continues, however. You must continue to cherish one
another, and you must continue to, upon the foundations of the last
few years, actively build an even stronger relationship. All the
lessons you've learned in that time, lessons of love, forgiveness, and
trust, you must continue to cultivate.

As you face the challenges of the years to come, remember the things
you did that brought you each to this place. Always be there to
provide the support, encouragement, and refuge that you partner needs.
Be present in your love and devoted to your mutual commitment. This
vow renewal ceremony provides you with the opportunity to, in front of
your loved ones, strengthen those sacred bonds, and reaffirm the
promises made in your hearts on your wedding day.

* Exchange of Vows

*Minister*: Jen and Rob, at this time I would invite you to share the
vows renewing your commitment with one another. Jen, would you like to
begin?

*Jen*: Marriage is a fragile thing, and one that has lasted as long as
ours is a precious rarity, to be held carefully and cherished forever.
I chose you before, and today I choose you again. Not because I
should, not because it is expected, but because my love for you is
even deeper and richer than it was the day I married you. I choose you
again gladly without reservation. I hereby reaffirm my vows to love
you, to comfort you, to honor you, and to keep you.

*Minister*: Rob, your turn.

*Rob*: Marriage is a fragile thing, and one that has lasted as long as
ours is a precious rarity, to be held carefully and cherished forever.
I chose you before, and today I choose you again. Not because I
should, not because it is expected, but because my love for you is
even deeper and richer than it was the day I married you. I choose you
again gladly without reservation. I hereby reaffirm my vows to love
you, to comfort you, to honor you, and to keep you.

* Declaration of Intent

*Minister*: Jen and Rob please join hands.

Jen, will you continue to have Rob as your husband, and recommit to
hold him close and cherish your relationship together?

*Jen*: I do.

Rob, will you continue to have Jen as your wife, and recommit to hold
her close and cherish your relationship together?

*Rob*: I do.

Jen please repeat after me. 

#+begin_quote

I Jen, take you, Rob by the hand, and
reaffirm my love for you. I will love, cherish, and honor you in all
the experiences that we have in life. This love will continue through
sickness and health, riches and poverty, for better or worse, so long
as we both shall live.

#+end_quote

Rob, please repeat after me. 

#+begin_quote

I Rob, take you, Jen by the hand, and
reaffirm my love for you. I will love, cherish, and honor you in all
the experiences that we have in life. This love will continue through
sickness and health, riches and poverty, for better or worse, so long
as we both shall live.

#+end_quote

* Candle-Lighting

Jen and Rob, while the words you have spoken have sealed your union,
it is the lighting of the unity candle that truly symbolizes the
melding of your two souls. At this time Jen and Rob should each
receive a pre-lit taper candle. You hold in your hands a single flame.

Allow this flame to represent your life: every thought that's ever
crossed your mind, and every word that's ever crossed your lips; all
of your victories, and all of your failures; all of your joys, and all
of your sorrows. And now, tilt these candles forward to light the
center candle. Jen and Rob should tilt their candles forward, lighting
a larger candle centered between them.

Watch as the two flames instantly form one. So too, today, have your
two spirits come together to form one singular entity. Just as your
combined flame illuminates the space around it, let your magnificent
union radiate with love and light your path as you move forward
through life.

* Pronouncement

*Minister*: I hereby pronounce Jen and Rob as still being happily
married! Your vows renewed, may your marriage move forward and become
stronger than you ever imagined.

* Kiss

*Minister*: Rob, at this time I would invite you to please seal the
renewal of your vows with a kiss!

* Presentation

*Minister*: Ladies and gentlemen, I'm delighted to present to you Mr.
and Mrs. Jen and Rob Farmer, committed again to one another before
God. From this day forth, may their joys be plenty and their worries
few as their love continues to grow.

